title: UK TV Global
description: Latest Hollywood & Bollywood News, Celebrity Updates, Box Office Reports & Upcoming Movie Leaks
url: https://uktvglobal.in
baseurl: ""

permalink: /:year/:month/:day/:title/

timezone: Asia/Kolkata

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown

kramdown:
  input: GFM
