title: UK TV Global
description: Latest Hollywood & Bollywood News, Celebrity Updates & Box Office Reports
url: https://uktvglobal.in
baseurl: ""

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
